name: Passport Queue Checker

on:
  schedule:
    # Запуск каждые 5 минут
    - cron: '*/5 * * * *'
  workflow_dispatch: # Позволяет запускать проверку вручную кнопкой

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Скачивание репозитория
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Установка библиотек
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install playwright
        playwright install chromium
        playwright install-deps

    - name: Запуск скрипта
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python passport.py
